spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:first-step}
      password: ${MONGO_PASSWORD:password}
      username: ${MONGO_USER:username}
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}:${spring.data.mongodb.port}

  application:
    name: first-step
  session:
    mongodb:
      collection-name: sessions

logging:
  level:
    org:
        springframework:
            data:
              mongodb:
                core:
                  MongoTemplate: DEBUG
                mongodb:
                  driver: DEBUG